package volvic.tyrannosaurusallen;

public enum JobEnum {
    APPS_MAILHANDLER,
    PIT_TRAINED_NON_DOCK_MAILHANDLER,
    ADUS_MAILHANDLER,
    DOCK_MAILHANDLER,
    LCUS_MAILHANDLER,
    STATES_MAILHANDLER,
    EXPEDITOR_CLERK,
    STATES_CLERK,
    LCUS_CLERK,
    LCUS_LOADER_MAILHANDLER,
    NON_EXPEDITOR_TRAINED_CLERK,
    SCANWAY_CLERK,
    PSE,
    MHA,

}
